# Generated by Django 4.2.7 on 2023-11-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empNo', models.IntegerField()),
                ('empName', models.CharField(max_length=20)),
                ('empSalary', models.FloatField()),
                ('empAddress', models.CharField(max_length=100)),
            ],
        ),
    ]
